### ISSUE TITLE
Working Fine on ST3

### ISSUE THREAD

**Issue by purplespider** [unphased/SublimeStatusbarPath#4]
Package Control (and therefore caniswitchtosublimetext3.com) report that this package only works on ST2. However, it appears to function fine on ST3.

**Comment by unphased** [comment]
Do you know what controls this status?

**Comment by Kikobeats** [comment]
how about this? :-)

**Comment by unphased** [comment]
What's "this"?

**Comment by Kikobeats** [comment]
registered in package control as ST3 compatible

**Comment by unphased** [comment]
Oh, nice. (I ditched ST for Vim btw. FWIW I miss it. The smooth scrolling. The sane scripting language)
